### ISSUE TITLE
Console says app.use is not a function

### ISSUE THREAD

**Issue by sudip-p** [laineus/vue3-smooth-scroll#1]
Using Vue3 with VueCLI. Followed all the steps of installation, and ran into an issue when I get to this:

`const app = createApp(...)`
`app.use(VueSmoothScroll)`

Other than imports, these are the only two lines in main.js, and the console reports this:

> Uncaught TypeError: app.use is not a function
    at eval (main.js?56d7:7)
    at Module../src/main.js (app.js:1253)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:1266)
    at __webpack_require__ (app.js:849)
    at checkDeferredModules (app.js:46)
    at app.js:925
    at app.js:928

`main.js?56d7:7` refers to `app.use(VueSmoothScroll)`

The following the only two lines I have in main.js:
`const app = createApp(App).mount('#app');`
`app.use(VueSmoothScroll)`

Please advise.

**Comment by laineus** [comment]
Thank you for your reporting. Let me check.

**Comment by laineus** [comment]
@sudip-p 

I got the cause.
`app::mount` will not return itself (app instance). It returns mounted component instance.

```js
const app = createApp(App)
const instanceOfAppComponent = app.mount('#app')
console.log(app === instanceOfAppComponent) // -> false
```

So please exec `use` for the app instance.

```js
const app = createApp(App).use(VueSmoothScroll)
app.mount('#app')
```

**Comment by sudip-p** [comment]
Thank you, that solved the problem. Starred your repo! 😄

**Comment by laineus** [comment]
Good luck!

**Comment by maxinzhi007** [comment]
Thank you！！！your answer  also solved my  problem !!!

**Comment by alice-njoroge** [comment]
thank you!!
