### ISSUE TITLE
`window` is not defined.

### ISSUE THREAD

**Issue by HappyTiptoe** [laineus/vue3-smooth-scroll#2]
This tool is supposedly SSR friendly, yet heavily makes use of the `window` global. What is your workaround for this?

**Comment by laineus** [comment]
@ebxn Thank for your reporting. and sorry for the inconvenience.

I fixed the bug, but it is not yet tested on a SSR project.
Could you please try this branch?
https://github.com/laineus/vue3-smooth-scroll/pull/3

```
$ npm install https://github.com/laineus/vue3-smooth-scroll.git#issue-2
# or
$ yarn add https://github.com/laineus/vue3-smooth-scroll.git#issue-2
```

**Comment by HappyTiptoe** [comment]
Hey @laineus,

Thanks for the swift reply - you have no idea how useful this tool was for me! Apologies for taking so long to get back to you - timezones and work and all of that!

I just tested this in my SSR boilerplate, and it worked flawlessly.

Thanks so much, and all the best!

**Comment by laineus** [comment]
@ebxn Thank you for your testing!

I just merged the branch and publish to npm repository.
Now you can install the new release by normal way.
